spring:
  application:
    name: eureka-server-cluster
  security:
    user:
      name: rongweijie
      password: 123456
  profiles:
    active: master

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    #关闭eureka自我保护
    enable-self-preservation: false
    #清理无效节点的时间间隔,默认60000毫秒,即60秒
    eviction-interval-timer-in-ms: 5000