spring:
  application:
    name: eureka-server-cluster
  security:
    user:
      name: rongweijie
      password: 123456
  profiles:
    active: master

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false

    