spring:
  application:
    name: hystrix-feign-demo

server:
  port: 1005

eureka:
  client:
    service-url:
      defaultZone: http://rongweijie:123456@192.168.1.12:8761/eureka/,http://rongweijie:123456@192.168.1.12:8762/eureka/
    healthcheck:
      #开启健康检查,需要导入actuator依赖包
      enabled: true
  instance:
    #通过ip地址注册
    prefer-ip-address: true
    ip-address: 192.168.1.12
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
    # euerka客户端发送给euerka客户端的心跳频率,默认30秒,现在设置为5秒
    lease-renewal-interval-in-seconds: 5
    # 表示euerka服务端至上一次收到euerka客户端的心跳之后,等待下一次心跳的超时时间,在这个时间内若没收到下一次心跳,则移除该instance,默认90秒,现在设置为5秒
    lease-expiration-duration-in-seconds: 5

feign:
  hystrix:
    enabled: true
