spring:
  application:
    name: eureka-client-user-service
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://rongweijie:123456@192.168.1.12:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.12
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}

